config/routes.rb
Rails.application.routes.draw do
  # mount ActionCable.server => '/cable'
  mount ActionCable.server => '/cable', constraints: { protocol: 'ws' }

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"

  namespace :api do
    post 'login', to: 'session#create'
    post 'comments', to: 'comments#create'
    post 'entries', to: 'entries#create'
    get 'patients', to: 'patients#index'
    get 'patients/search', to: 'patients#search'
    post 'profiles', to: 'profiles#update'
    # post 'patients', to: 'patients#new'
  end

  # Ajax Filters
  get 'patients/filter', to: 'users#filter', as: :patients_filter
  get 'indicators/filter', to: 'indicators#filter', as: :indicators_filter
  get 'meals/filter', to: 'meals#filter', as: :meals_filter
  get 'conditions/filter', to: 'conditions#filter', as: :conditions_filter

  resources :activity_factors
  resources :contact_us
  resources :roles
  resources :genders
  resources :discounts
  resources :products
  resources :indicator_types
  resources :indicators
  resources :packages
  resources :instant_sessions
  resources :appointments
  resources :availabilities
  resources :tasks
  resources :bmr_factors
  resources :conditions
  resources :meals
  resources :restricted_ingredient_conditions

  resources :diets
  post 'diets/session/:session_id', to: 'diets#create_diet_session', as: :create_diet_session

  get 'render_chat_partial/:id', to: 'conversations#render_chat_partial'
  resources :conversations do
    resources :notes
  end
  resources :entries do
    resources :emoji_reactions, only: [:create]

    resources :comments do
      resources :emoji_reactions, only: [:create]
    end
  end

  resources :billings do
    post '/billing_items/create', to: 'billing_items#create', as: :items_create
    # post '/paid_items/create', to: 'payments#create', as: :paid_items_create
    post '/payment/create', to: 'payments#create', as: :create_payment
    # get '/billing_items', to: 'billing_items#index', as: :items
    delete '/billing_items/:id', to: 'billing_items#destroy', as: :items_destroy
    # get '/billing_items/new', to: 'billing_items#new', as: :items_new
    post '/payments/create', to: 'payments#create', as: :payments_create
    delete '/payments/payment_items/:id', to: 'payment_billing_items#destroy', as: :payment_items_destroy
  end

  # get 'signup', to: 'users#new'
  # post 'signup', to: 'users#create'
  get 'login', to: 'authentication#login', as: :login
  post 'login', to: 'authentication#authenticate'
  delete 'logout', to: 'authentication#logout', as: :destroy_user_session

  post '/charts/sessionsjson', to: 'charts#sessionsjson'

  # global
  patch 'update_dolar_price/:id', to: 'application#update_dolar_price', as: :patch_update_dolar_price

  patch 'patients/:id', to: 'users#update', as: :patch_patient
  post 'patients', to: 'users#create', as: :post_patients
  post 'instant_patient/:id', to: 'users#create_from_instant', as: :create_patient_from_instant_session
  resources :patients, controller: 'users', type: 'User' do
    post '/patient_conditions', to: 'patient_conditions#create', as: :post_patient_conditions
    delete '/patient_conditions/:id', to: 'patient_conditions#destroy', as: :destroy_patient_conditions
    get '/packagesjson', to: 'patient_packages#packagesjson'
    #PACKAGES
    get '/patient_packages/new', to: 'patient_packages#new', as: :package_new
    get '/patient_packages/:id', to: 'patient_packages#show', as: :package_show
    post '/patient_packages/create', to: 'patient_packages#create', as: :package_create

    resources :patient_packages do
      get '/sessions/new', to: 'sessions#new', as: :new_session
      get '/sessions/:id', to: 'sessions#show', as: :session_show
      get '/sessions/:id/edit', to: 'sessions#edit', as: :edit_session
      patch '/session/:id/update', to: 'sessions#update', as: :update_session
      post '/sessions/create', to: 'sessions#create', as: :create_session
    end
  end

  get "dashboard", to: "dashboard#index"
  root 'dashboard#index'
  # root 'examples#index'

  resources :examples, only: :index do
    get :buttons, :cards, :utilities_color, :utilities_border,
        :utilities_animation, :utilities_other,
        :forgot_password, :page_404, :blank, :charts, :tables,
        on: :collection
  end
end

app/models/conversation.rb
# frozen_string_literal: true

# Conversation model
class Conversation < ApplicationRecord
  belongs_to :dietitian, class_name: 'User', foreign_key: 'dietitian_id'
  belongs_to :patient, class_name: 'User', foreign_key: 'patient_id'

  has_many :notes
end

app/controllers/conversations_controller.rb
# frozen_string_literal: true

# ConversationsController
class ConversationsController < ApplicationController
  before_action :set_conversation, only: %i[show edit update destroy]
  before_action :set_conversations, only: %i[index create update destroy]

  # GET /conversations or /conversations.json
  def index
    @conversation ||= Conversation.find_by(id: params[:convo_id])

    mark_notification_seen if @conversation && params[:convo_id].present?
  end

  # GET /conversations/1 or /conversations/1.json
  def show
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
  end

  # GET /conversations/1/edit
  def edit
  end

  # POST /conversations or /conversations.json
  def create
    @conversation = Conversation.new(conversation_params)

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to conversation_url(@conversation), notice: "Conversation was successfully created." }
        format.js { render 'conversations/index', layout: false }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /conversations/1 or /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to conversation_url(@conversation), notice: "Conversation was successfully updated." }
        format.json { render :show, status: :ok, location: @conversation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1 or /conversations/1.json
  def destroy
    @conversation.destroy

    respond_to do |format|
      format.html { redirect_to conversations_url, notice: "Conversation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def render_chat_partial
    @conversation = Conversation.find(params[:id])
    @notes = @conversation.notes.includes(:patient) # Carga las asociaciones notes y patient

    # Renderizar el parcial y obtener el contenido como una cadena
    chat_partial_html = render_to_string(partial: 'conversations/chat', locals: { conversation: @conversation, notes: @notes })

    render plain: chat_partial_html
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end

    def set_conversations
      @conversations = current_user.dietitian_conversations
    end

    # Only allow a list of trusted parameters through.
    def conversation_params
      # params.fetch(:conversation, {})
      params.require(:conversation).permit(:patient_id).merge(dietitian_id: current_user.id)
    end

    def mark_notification_seen
      # @conversation.update(seen: true) if !@conversation.seen

      note_ids = @conversation.notes.where(seen: false).select(:id)
      recipient_id = @conversation.dietitian_id

      Notification.where(
        recipient_id: recipient_id,
        associated_object_id: note_ids,
        notification_type: :note
      ).update_all(seen: true)
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_chat.html.erb
<% if conversation %>
  <div class="col-sm-12 col-md-10 col-lg-9 col-xl-8 mb-5 p-0">
    <div class="card p-0 border-secondary-300">
        <!-- Cabecera de la converzacion -->
        <div class="card-header bg-secondary-500 text-white-01 d-flex justify-content-between align-items-center px-0 py-2">
          <div class="px-2">
            <img src="" alt="profile" tile="profile">
          </div>
          <div class="d-flex flex-column flex-grow-1 px-2">
              <span>
                <%= link_to patient_path(conversation.patient.id), class: 'text-secondary-10' do %>
                  <%= conversation.patient.full_name %>
                <% end %>
              </span>
              <span class='text-white-01'><%= conversation.created_at.strftime('%b %-d at %I:%M:%P') %></span>
          </div>
        </div>
        <div class="card-body px-0 pt-0 h-400px overflow-hidden" id="content-notes">
            <!-- Renderizamos las notas -->
          <div class="px-3 h-100 overflow-y-scroll" id="content-notes-scoll">
              <div id="notes-partial" class="d-flex flex-column ">
                <%= render 'conversations/note', notes: conversation.notes%>
              </div>
          </div>
        </div>

        <div class="px-2 py-2 bg-secondary-500">
          <!-- Renderizamos los emojis -->
          <div class="d-flex flex-start mb-2">
            <div class="border-radius-40 d-flex justify-content-center">
              <span class="px-0 p-0 m-0 pl-2 d-flex emoji-panel" id="emoji-panel">
                <%= render "layouts/components/emojis", action_call: 'addEmoji(event)' %>
              </span>
            </div>
          </div>

          <!-- Renderizamos el formulario para comentar -->
          <%= simple_form_for([conversation, Note.new],
            data: { type: :json }, html: { class: 'd-flex justify-between items-center',
            id:"conversation_form", remote: true
          }) do |f| %>
            <input
            id="messageInput" type="text" name="note[message]" placeholder="Escribe tu mensaje..."
            class="flex-grow-1 pl-2 mx-2 border-radius-40 border-0"
            />
            <input type="submit"
            name="commit" onclick="addComment(event)" value="Crear"
            class="btn btn-primary text-wghite-01 border-radius-40 px-2"
            id="create_comment_button" data-disable-with="Crear" style="color: white;">
          <% end %>
        </div>
    </div>
  </div>
<% end %>

app/views/conversations/_conversations.html.erb
<% conversations.map do |conversation|%>
  <div class="pt-2">
    <%= link_to "/conversations?convo_id=#{conversation.id}", class: 'text-decoration-none' do %>
      <%= conversation.patient.full_name %>
    <% end %>
  </div>
<% end %>

app/views/conversations/_form.html.erb
<%= simple_form_for(@conversation) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/conversations/_note.html.erb
<% notes.map do |note| %>
   <% if current_user == note.user %>
      <div class="p-0 py-3 d-flex items-center" style="align-self: end;">
      <div class="d-flex pr-2 flex-column">
         <span class="d-flex justify-content-end">
            <span class="f-size-12"><%= note.created_at.strftime('%b %-d at %I:%M:%P') %></span>&nbsp; - &nbsp;<strong><%= note.user.first_name_initial %></strong>
         </span>
         <p class="m-0 d-flex justify-content-end"><%= note.message %></p>

      </div>
      <div>
         <div class="border-radius-40 bg-pink-100 p-2">
            <strong class=""><%= note.user.get_initials %></strong>
         </div>
      </div>
   </div>
   <% else %>
   <div class="p-0 py-2 d-flex items-center">
      <div>
         <div class="border-radius-40 bg-pink-100 p-2">
            <strong class=""><%= note.user.get_initials %></strong>
         </div>
      </div>
      <div class="d-flex pl-2 flex-column">
         <span class="d-flex">
            <strong><%= note.user.first_name_initial %></strong>&nbsp; - &nbsp;<span class="f-size-12"><%= note.created_at.strftime('%b %-d at %I:%M:%P') %></span>
         </span>
         <p class="m-0"><%= note.message %></p>

      </div>
   </div>
   <% end %>
<% end %>

app/views/conversations/edit.html.erb
<h1>Editing Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<div class="col-12">
  <div class="d-flex flex-column flex-grow-1" style="height: 576px;">
    <div id="conversations-list-id" style="border: solid 1px gray;" class="w-200px p-3 d-none">
      <button type="button" class="btn btn-primary mb-2" data-toggle="modal" data-target="#newConversationModal">
        New Conversation
      </button>
      <header class="p-0 pb-3">Conversations (<%= @conversations.count %>)</header>
      <section id='conversations_section'>
        <%= render 'conversations', conversations: @conversations %>
      </section>
    </div>
    <div class="d-flex flex-column justify-content-center px-2">
      <button id="btn-open-conversation-aside" class="btn btn-link btn-transparent p-0">
        <%= render "layouts/components/icons", type: 'arrow-bar-right', height: '20', width: '20', color: 'purple' %>
      </button>
    </div>
    <div class="flex-grow-1 d-flex justify-content-center" id='current_conversation'>
      <%= render 'chat', conversation: @conversation %>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="newConversationModal" tabindex="-1" role="dialog" aria-labelledby="newConversationModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Select Patient</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with scope: Conversation.new,
          url: conversations_path,
          data: { type: :json },
          html: {
            id:"new_conversation_form_id",
            class: 'mx-4 h-auto',
            multipart: true,
            remote: true} do |f| %>
          <div class="form-group">
            <label for="discount_id">Patient</label>
            <%= f.select(:patient_id, options_for_select(User.active_patients.map {|k| [k.full_name.to_s.humanize, k.id]}, :selected => nil ), {}, {:required => true ,:class => 'form-control'}) %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" onclick="create_conversation()">Create</button>
      </div>
    </div>
  </div>
</div>


<% content_for :javascript do %>
  <script>
    function scroll_down() {
      const myDiv = document.getElementById('content-notes-scoll');
      if (myDiv) {
        myDiv.scrollTop = myDiv.scrollHeight;
      }
    }
    $(document).on('turbolinks:load', function() {
      scroll_down()
    });

    $(document).on('click','#btn-open-conversation-aside',function(e) {
      $("#conversations-list-id").toggleClass('d-none');
      $("#conversations-list-id").toggleClass('w-200px');
    });

    function sendComment() {
      let dataToSubmit = $("#conversation_form").serialize();
      console.log('dataToSubmit', dataToSubmit)
      $.ajax({
        url: $("#conversation_form").attr('action'),
        type: "POST",
        data: dataToSubmit,
        dataType: "script",
        success: function(data) {
          $("#messageInput").val('');
           scroll_down()
        },
        error: function(err) {
          console.log('err', err);
        }
      })
    }

    function addComment(event) {
      event.preventDefault();
      sendComment()
    }

    function addEmoji(event) {
      const inputField = document.getElementById('messageInput');
      const emoji = event.target.value

      if (inputField === document.activeElement) {
        // Obtiene la posición actual del cursor
        var start = inputField.selectionStart;
        var end = inputField.selectionEnd;

        // Inserta el emoji en la posición actual del cursor
        inputField.value = inputField.value.substring(0, start) + emoji + inputField.value.substring(end);

        // Mueve el cursor después del emoji insertado
        var newCursorPosition = start + emoji.length;
        inputField.setSelectionRange(newCursorPosition, newCursorPosition);
      } else {
        inputField.value += emoji;
      }
    }

    //******************
    //* Create billing item
    //*
    function create_conversation() {
        var dataToSubmit = $("#new_conversation_form_id").serialize();
        console.log('dataToSubmit', dataToSubmit);
        // document.getElementById('new_conversation_form_id').submit();
         $.ajax({
           url: $("#new_conversation_form_id").attr('action'),
           type: "POST",
           data: dataToSubmit,
           // contentType: "application/json; charset=utf-8",
           dataType: "script",
           success: function(data) {
            customCloseModal('newConversationModal');
           },
           error: function(err) {
             console.log('err', err);
           }
         })
    }
  </script>
<% end %>

app/views/conversations/index.js.erb
$("#conversations_section").html("\
		<%= escape_javascript(render(:partial => 'conversations/conversations', :locals => {\
																 :conversations => @conversations} )) %>");

$("#current_conversation").html("\
		<%= escape_javascript(render(:partial => 'conversations/chat', :locals => {\
																 :conversation => @conversation} )) %>");

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_conversation_path(@conversation) %> |
<%= link_to 'Back', conversations_path %>