config/routes.rb
Rails.application.routes.draw do
  # mount ActionCable.server => '/cable'
  mount ActionCable.server => '/cable', constraints: { protocol: 'ws' }

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"

  namespace :api do
    post 'login', to: 'session#create'
    post 'comments', to: 'comments#create'
    post 'entries', to: 'entries#create'
    get 'patients', to: 'patients#index'
    get 'patients/search', to: 'patients#search'
    post 'profiles', to: 'profiles#update'
    # post 'patients', to: 'patients#new'
  end

  # Ajax Filters
  get 'patients/filter', to: 'users#filter', as: :patients_filter
  get 'indicators/filter', to: 'indicators#filter', as: :indicators_filter
  get 'meals/filter', to: 'meals#filter', as: :meals_filter
  get 'conditions/filter', to: 'conditions#filter', as: :conditions_filter

  resources :activity_factors
  resources :contact_us
  resources :roles
  resources :genders
  resources :discounts
  resources :products
  resources :indicator_types
  resources :indicators
  resources :packages
  resources :instant_sessions
  resources :appointments
  resources :availabilities
  resources :tasks
  resources :bmr_factors
  resources :conditions
  resources :meals
  resources :restricted_ingredient_conditions

  resources :diets
  post 'diets/session/:session_id', to: 'diets#create_diet_session', as: :create_diet_session

  get 'render_chat_partial/:id', to: 'conversations#render_chat_partial'
  resources :conversations do
    resources :notes
  end
  resources :entries do
    resources :emoji_reactions, only: [:create]

    resources :comments do
      resources :emoji_reactions, only: [:create]
    end
  end

  resources :billings do
    post '/billing_items/create', to: 'billing_items#create', as: :items_create
    # post '/paid_items/create', to: 'payments#create', as: :paid_items_create
    post '/payment/create', to: 'payments#create', as: :create_payment
    # get '/billing_items', to: 'billing_items#index', as: :items
    delete '/billing_items/:id', to: 'billing_items#destroy', as: :items_destroy
    # get '/billing_items/new', to: 'billing_items#new', as: :items_new
    post '/payments/create', to: 'payments#create', as: :payments_create
    delete '/payments/payment_items/:id', to: 'payment_billing_items#destroy', as: :payment_items_destroy
  end

  # get 'signup', to: 'users#new'
  # post 'signup', to: 'users#create'
  get 'login', to: 'authentication#login', as: :login
  post 'login', to: 'authentication#authenticate'
  delete 'logout', to: 'authentication#logout', as: :destroy_user_session

  post '/charts/sessionsjson', to: 'charts#sessionsjson'

  # global
  patch 'update_dolar_price/:id', to: 'application#update_dolar_price', as: :patch_update_dolar_price

  patch 'patients/:id', to: 'users#update', as: :patch_patient
  post 'patients', to: 'users#create', as: :post_patients
  post 'instant_patient/:id', to: 'users#create_from_instant', as: :create_patient_from_instant_session
  resources :patients, controller: 'users', type: 'User' do
    post '/patient_conditions', to: 'patient_conditions#create', as: :post_patient_conditions
    delete '/patient_conditions/:id', to: 'patient_conditions#destroy', as: :destroy_patient_conditions
    get '/packagesjson', to: 'patient_packages#packagesjson'
    #PACKAGES
    get '/patient_packages/new', to: 'patient_packages#new', as: :package_new
    get '/patient_packages/:id', to: 'patient_packages#show', as: :package_show
    post '/patient_packages/create', to: 'patient_packages#create', as: :package_create

    resources :patient_packages do
      get '/sessions/new', to: 'sessions#new', as: :new_session
      get '/sessions/:id', to: 'sessions#show', as: :session_show
      get '/sessions/:id/edit', to: 'sessions#edit', as: :edit_session
      patch '/session/:id/update', to: 'sessions#update', as: :update_session
      post '/sessions/create', to: 'sessions#create', as: :create_session
    end
  end

  get "dashboard", to: "dashboard#index"
  root 'dashboard#index'
  # root 'examples#index'

  resources :examples, only: :index do
    get :buttons, :cards, :utilities_color, :utilities_border,
        :utilities_animation, :utilities_other,
        :forgot_password, :page_404, :blank, :charts, :tables,
        on: :collection
  end
end

app/models/bmr_factor.rb
# frozen_string_literal: true

# BmiFactor model
class BmrFactor < ApplicationRecord
  belongs_to :gender
  belongs_to :created_by, class_name: 'User', foreign_key: 'created_by_id'

  paginates_per 8

  before_save :trim_values

  private

  def trim_values
  	self.name = name.strip
  end
end

app/controllers/bmr_factors_controller.rb
# frozen_string_literal: true

# BmrFactorsController
class BmrFactorsController < ApplicationController
  before_action :check_auth_for_all_origin
  before_action :set_bmr_factor, only: %i[ show edit update destroy ]

  # GET /indicators or /indicators.json
  def index
    @bmr_factors = BmrFactor.order(:id, :source).page(params[:page] || 1)
  end

  # GET /indicators/1 or /indicators/1.json
  def show
    @genders = Gender.all
  end

  # GET /indicators/new
  def new
    @bmr_factor = BmrFactor.new
    @genders = Gender.all
  end

  # GET /indicators/1/edit
  def edit
    @genders = Gender.all
  end

  # POST /indicators or /indicators.json
  def create
    @bmr_factor = BmrFactor.new(bmr_params.merge(created_by_id: current_user.id))

    respond_to do |format|
      if @bmr_factor.save
        format.html { redirect_to bmr_factors_path, notice: "Bmr Factor was successfully created." }
        format.json { render :json, status: :created, location: @bmr_factor }
      else

        format.html { render :index, status: :unprocessable_entity }
        format.json { render json: @bmr_factor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /indicators/1 or /indicators/1.json
  def update
    respond_to do |format|
      if @bmr_factor.update(bmr_params)
        format.html { redirect_to bmr_factors_path, notice: "Bmr Factor was successfully updated." }
        format.json { render :show, status: :ok, location: @bmr_factor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bmr_factor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indicators/1 or /indicators/1.json
  def destroy
    @bmr_factor.destroy
    respond_to do |format|
      format.html { redirect_to bmr_factors_path, notice: "Bmr Factor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bmr_factor
      @bmr_factor = BmrFactor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bmr_params
      params.require(:bmr_factor)
            .permit(
              :base_value,
              :base_height,
              :base_weight,
              :base_age,
              :name,
              :position,
              :source,
              :gender_id
            )
    end
end

app/helpers/bmr_factors_helper.rb
module BmrFactorsHelper
end

app/views/bmr_factors/_form.html.erb
<div class="col-xs-12 col-sm-10 col-md-8 col-lg-6 mx-auto">
  <%= render Forms::FormComponent.new(
      scope_instance: bmr_factor,
      is_row: true,
      data_type: { type: :json },
      html_options: { id:"bmr_factor_form_id", class: 'form', remote: false},
      action_buttons: {},
      fields: [
            {
              type: 'number', name: :base_value, label: :base_value,
              value: bmr_factor.base_value,
              input_class: ''
            },
            {
              type: 'number', name: :base_height, label: :base_height,
              value: bmr_factor.base_height,
              input_class: ''
            },
            {
              type: 'number', name: :base_weight, label: :base_weight,
              value: bmr_factor.base_weight,
              input_class: ''
            },
            {
              type: 'number', name: :base_age, label: :base_age,
              value: bmr_factor.base_age,
              nput_class: ''
            },
            {
              type: 'text', name: :name, label: :name, value: bmr_factor.name,
              nput_class: ''
            },
            {
              type: 'number', name: :position, label: :position,
              value: bmr_factor.position,
              nput_class: ''
            },
            {
              type: 'number', name: :source, label: :source,
              value: bmr_factor.source,
              nput_class: ''
            },
            {
              type: 'select', name: :gender_id, label: :gender,
              nput_class: '',
              collection: { data: @genders,
                label_method: :name,
                selected: bmr_factor.gender_id,
              },
            }
          ],
  ) %>
</div>

app/views/bmr_factors/_list.html.erb
<%= render Elements::TableComponent.new(
  row_objects: @bmr_factors,
  table_alias: @bmr_factors.model.name.underscore,
  row_fields: [
    # { field: :name, link: ->(label, object) { link_to(label, gender_path(object)) }},
    { field: :name },
    { field: :base_value },
    { field: :base_height },
    { field: :base_weight },
    { field: :base_age },
    { field: :position },
    { field: :source },
    { field: 'gender.name', label: 'gender' },
    { field: 'created_by.full_name', label: 'created_by' },
  ],
  row_actions: {}
) %>

app/views/bmr_factors/edit.html.erb
<%= render 'form', bmr_factor: @bmr_factor %>

app/views/bmr_factors/index.html.erb
<div class="col-12">
  <h1>Bmr Factors</h1>
  <div class="w-100 text-right mb-4">
    <%= link_to 'New', new_bmr_factor_path , class: "btn btn-primary" %>
  </div>

  <div class="d-flex justify-content-center">
    <%= render 'paginations/pagination', objectData: @bmr_factors %>
  </div>

  <div id="bmr_factors_list_partial">
    <%= render 'list', bmr_factors: @bmr_factors %>
  </div>
</div>

app/views/bmr_factors/new.html.erb
<%= render 'form', indicator: @indicator, title: "indicators.new_indicator", action_button: 'indicators.form.create_indicator', editing: false %>

app/views/bmr_factors/show.html.erb
<%= render Elements::Card::CardComponent.new(
    header_tabs: [
      { label: 'BMR Factor Info', target: '#info' },
    ],
    extra_item_options: [
      { element: ->() {
        link_to 'Edit', edit_bmr_factor_path(@bmr_factor)
      }}
    ],
    card_class: '',
    card_body_class: 'tab-content p-2',
    card_component_id: 'billings_info_component'
  ) do %>
    <div id="info" class="tab-pane active" role="tabpanel">
      <%= render Elements::TableShowComponent.new(
        row_object: @bmr_factor,
        table_alias: @bmr_factor.model_name.to_s.downcase,
        table_class: 'table-borderless',
        row_fields: [
          { field: :name, classes: 'text-primary-400' },
          { field: :base_value, classes: 'text-primary-400' },
          { field: :base_height, classes: 'text-primary-400' },
          { field: :base_weight, classes: 'text-primary-400' },
          { field: :base_age, classes: 'text-primary-400' },
          { field: 'gender.name', label: 'gender', classes: 'text-primary-400' },
          { field: :position, classes: 'text-primary-400' },
          { field: :source, classes: 'text-primary-400' },
          { field: 'created_by.full_name', label: 'created_by', classes: 'text-primary-400' },
        ]
      )%>
    </div>
  <% end %>
  <div class="d-flex col-12 align-items-center justify-content-center my-2">
    <%= link_to 'Back', bmr_factors_path, class: "text-primary-700" %>
  </div>